
include("roundedbox_poly.lua")

local drawRoundedAvatar = function(avatar, borderRadius)
	render.ClearStencil()
	render.SetStencilEnable(true)
	render.SetStencilWriteMask(1)
	render.SetStencilTestMask(1)
	render.SetStencilCompareFunction(STENCILCOMPARISONFUNCTION_NEVER)
	render.SetStencilFailOperation(STENCILOPERATION_REPLACE)
	render.SetStencilPassOperation(STENCILOPERATION_ZERO)
	render.SetStencilZFailOperation(STENCILOPERATION_ZERO)
	render.SetStencilReferenceValue(1)
	local x, y = avatar:GetPos()
	local w, h = avatar:GetSize()
	draw.RoundedBoxPoly(borderRadius, x, y, w, h)
	render.SetStencilFailOperation(STENCILOPERATION_ZERO)
	render.SetStencilPassOperation(STENCILOPERATION_REPLACE)
	render.SetStencilZFailOperation(STENCILOPERATION_ZERO)
	render.SetStencilCompareFunction(STENCILCOMPARISONFUNCTION_EQUAL)
	render.SetStencilReferenceValue(1)
	avatar:PaintManual()
	render.SetStencilEnable(false)
	render.ClearStencil()
end

local avatar = vgui.Create("AvatarImage")
avatar:SetSize(64, 64)
avatar:SetPlayer(LocalPlayer(), 64)
avatar:SetPaintedManually(true)

hook.Add("HUDPaint", "AvatarRenderAttempt", function()
	avatar:SetPos(10, ScrH() / 2 - avatar:GetTall() / 2)
	surface.SetDrawColor(255, 255, 255, 255)
	drawRoundedAvatar(avatar, avatar:GetWide() / 9)
	surface.SetDrawColor(255, 0, 0, 100)
	surface.DrawRect(0, 0, ScrW(), ScrH())
end)